#!/usr/bin/env bash
cd /path/to/script
source ./path/where/s3/credetials/stored
s3cmd del s3://<bucketname>/<s3path/\*
unloaddate=`date '+%Y-%m-%d' -d "-30 days"`
echo $unloaddate
export PGPASSWORD=<database password>
psql -h ${HOST}  -U ${USERNAME} -p ${PORT} -d ${DATABASE_NAME} <<EOF 
unload ('select * from ${production_schema}.<tablename> where local_proc_date >= \'${unloaddate} 00:00:00\'') to 's3://<bucketname>/<s3path>/<tablename>_' credentials 'aws_access_key_id=${ACCESS};aws_secret_access_key=${SECRET}' manifest;
unload ('select * from ${production_schema}.<tablename> where local_proc_date >= \'${unloaddate} 00:00:00\'') to 's3://<bucketname>/<s3path>p/<tablename>_' credentials 'aws_access_key_id=${ACCESS};aws_secret_access_key=${SECRET}' manifest;
unload ('select * from ${production_schema}.<tablename> where local_proc_date >= \'${unloaddate} 00:00:00\'') to's3://<bucketname>/<s3path>/<tablename>_' credentials 'aws_access_key_id=${ACCESS};aws_secret_access_key=${SECRET}' manifest;
unload ('select * from ${production_schema}.<tablename> where local_proc_date >= \'${unloaddate} 00:00:00\'') to 's3://<bucketname>/<s3path>/<tablename>_' credentials 'aws_access_key_id=${ACCESS};aws_secret_access_key=${SECRET}' manifest;
EOF
